### ISSUE TITLE
Rollenmatrix vorbereiten

### ISSUE THREAD

**Issue by Oderik** [nerdshop/asinello#1]
- [Rollenmatrix](https://github.com/nerdshop/asinello/wiki/Rollen) anlegen
- Erklärende Beschreibung formulieren
- Ggf. Querverweise zu [Projektzieldefinition](https://github.com/nerdshop/asinello/wiki/Projektziel)?
- Soweit Erinnerung vorhanden Personen gemäß letzter Besprechung eintragen
- Leute von Threema zur Matrix lotzen

**Comment by avanc** [comment]
Erledigt
